### ISSUE TITLE
Adopt Stylus syntax instead of css

### ISSUE THREAD

**Issue by superguigui** [hellohikimori/coding-style#1]
Should we instead use the stylus syntaxe ie no brackets, colons and semicolons ?

**Comment by vdaguenet** [comment]
I use this syntaxe in my personal projects and I find it clarified, more readable.
But, it needs to strongly respect the convention. I always add a blank line between blocks

``` css
.MyClass
  background red

  &-child
    color blue
```

**Comment by superguigui** [comment]
Agreed. If @LaetitiaNanni is ok we can move forward with this motion :hammer:.

**Comment by letinani** [comment]
That works for me.
